ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "trial_ends_at" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "subscription_status" VARCHAR(20) NOT NULL DEFAULT 'TRIAL';

ALTER TABLE "teachers"
ADD COLUMN IF NOT EXISTS "trial_ends_at" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "subscription_status" VARCHAR(20) NOT NULL DEFAULT 'TRIAL';
