-- PostgreSQL-safe backfill for runtime columns that can drift outside Prisma migrations.
-- This migration is additive and idempotent.

-- 1) student_preferences.response_language (immediate fix)
ALTER TABLE IF EXISTS "student_preferences"
  ADD COLUMN IF NOT EXISTS "response_language" VARCHAR(10) NOT NULL DEFAULT 'en';

-- 2) child_sessions table (if your DB has external child-session tracking)
CREATE TABLE IF NOT EXISTS "child_sessions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "child_id" BIGINT NOT NULL,
  "login_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "logout_at" TIMESTAMP(3),
  "duration_mins" INTEGER,
  "ip_address" VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS "idx_child_sess" ON "child_sessions" ("child_id");
CREATE INDEX IF NOT EXISTS "idx_login_at" ON "child_sessions" ("login_at");

-- 3) children table: trial fields + supabase uid
DO $$
BEGIN
  IF to_regclass('public.children') IS NOT NULL THEN
    ALTER TABLE "children"
      ADD COLUMN IF NOT EXISTS "trial_ends_at" TIMESTAMP(3),
      ADD COLUMN IF NOT EXISTS "subscription_status" VARCHAR(20) NOT NULL DEFAULT 'TRIAL',
      ADD COLUMN IF NOT EXISTS "supabase_uid" VARCHAR(36);

    UPDATE "children"
    SET "trial_ends_at" = NOW() + INTERVAL '3 days'
    WHERE "trial_ends_at" IS NULL;
  END IF;
END $$;

-- 4) parents table: trial fields
DO $$
BEGIN
  IF to_regclass('public.parents') IS NOT NULL THEN
    ALTER TABLE "parents"
      ADD COLUMN IF NOT EXISTS "trial_ends_at" TIMESTAMP(3),
      ADD COLUMN IF NOT EXISTS "subscription_status" VARCHAR(20) NOT NULL DEFAULT 'TRIAL';

    UPDATE "parents"
    SET "trial_ends_at" = NOW() + INTERVAL '3 days'
    WHERE "trial_ends_at" IS NULL;
  END IF;
END $$;

-- 5) teachers table: trial fields
DO $$
BEGIN
  IF to_regclass('public.teachers') IS NOT NULL THEN
    ALTER TABLE "teachers"
      ADD COLUMN IF NOT EXISTS "trial_ends_at" TIMESTAMP(3),
      ADD COLUMN IF NOT EXISTS "subscription_status" VARCHAR(20) NOT NULL DEFAULT 'TRIAL';

    UPDATE "teachers"
    SET "trial_ends_at" = NOW() + INTERVAL '3 days'
    WHERE "trial_ends_at" IS NULL;
  END IF;
END $$;

-- 6) users-style tables: trial fields
DO $$
BEGIN
  IF to_regclass('public.users') IS NOT NULL THEN
    ALTER TABLE "users"
      ADD COLUMN IF NOT EXISTS "trial_ends_at" TIMESTAMP(3),
      ADD COLUMN IF NOT EXISTS "subscription_status" VARCHAR(20) NOT NULL DEFAULT 'TRIAL';

    UPDATE "users"
    SET "trial_ends_at" = NOW() + INTERVAL '3 days'
    WHERE "trial_ends_at" IS NULL;
  END IF;

  IF to_regclass('public."User"') IS NOT NULL THEN
    ALTER TABLE "User"
      ADD COLUMN IF NOT EXISTS "trial_ends_at" TIMESTAMP(3),
      ADD COLUMN IF NOT EXISTS "subscription_status" VARCHAR(20) NOT NULL DEFAULT 'TRIAL';

    UPDATE "User"
    SET "trial_ends_at" = NOW() + INTERVAL '3 days'
    WHERE "trial_ends_at" IS NULL;
  END IF;
END $$;

-- 7) assignments.is_late
DO $$
BEGIN
  IF to_regclass('public.assignments') IS NOT NULL THEN
    ALTER TABLE "assignments"
      ADD COLUMN IF NOT EXISTS "is_late" BOOLEAN NOT NULL DEFAULT false;
  END IF;

  IF to_regclass('public."Assignment"') IS NOT NULL THEN
    ALTER TABLE "Assignment"
      ADD COLUMN IF NOT EXISTS "is_late" BOOLEAN NOT NULL DEFAULT false;
  END IF;
END $$;

-- 8) queries / SearchQuery content flagging columns
DO $$
BEGIN
  IF to_regclass('public.queries') IS NOT NULL THEN
    ALTER TABLE "queries"
      ADD COLUMN IF NOT EXISTS "is_flagged" BOOLEAN NOT NULL DEFAULT false,
      ADD COLUMN IF NOT EXISTS "flag_reason" VARCHAR(255);
  END IF;

  IF to_regclass('public."SearchQuery"') IS NOT NULL THEN
    ALTER TABLE "SearchQuery"
      ADD COLUMN IF NOT EXISTS "is_flagged" BOOLEAN NOT NULL DEFAULT false,
      ADD COLUMN IF NOT EXISTS "flag_reason" VARCHAR(255);
  END IF;
END $$;
