/**
 * ELEVENLABS TTS CONTRACT
 * Provider: ElevenLabs TTS API
 * Voices: HOST + COHOST + ANSWER
 * Script: Gemini produces tagged dialogue: [HOST] / [COHOST]
 * Audio: each speaker segment generated independently
 * Q&A: answer generated by Gemini, spoken by ANSWER voice
 * Storage: Supabase podcasts bucket
 * Access control happens in API route via hasFeatureAccess()
 */

import { ElevenLabsClient } from 'elevenlabs'
import { createClient } from '@supabase/supabase-js'
import { v4 as uuidv4 } from 'uuid'

const REQUIRED_ENV = [
  'ELEVENLABS_API_KEY',
  'ELEVENLABS_HOST_VOICE_ID',
  'ELEVENLABS_COHOST_VOICE_ID',
  'ELEVENLABS_ANSWER_VOICE_ID',
  'NEXT_PUBLIC_SUPABASE_URL',
  'SUPABASE_SERVICE_ROLE_KEY',
]

const missing = REQUIRED_ENV.filter((key) => !process.env[key])
if (missing.length > 0) {
  console.error('[ElevenLabs] Missing env vars:', missing.join(', '))
}

const eleven = new ElevenLabsClient({
  apiKey: process.env.ELEVENLABS_API_KEY,
})

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL ?? '',
  process.env.SUPABASE_SERVICE_ROLE_KEY ?? '',
)

const STORAGE_BUCKET = 'podcasts'

const VOICE_IDS = {
  HOST: process.env.ELEVENLABS_HOST_VOICE_ID ?? '',
  COHOST: process.env.ELEVENLABS_COHOST_VOICE_ID ?? '',
  ANSWER: process.env.ELEVENLABS_ANSWER_VOICE_ID ?? '',
} as const

const MODEL_ID = process.env.ELEVENLABS_MODEL_ID ?? 'eleven_flash_v2_5'
const FALLBACK_MODEL_IDS = ['eleven_multilingual_v2', 'eleven_turbo_v2_5']

function getModelChain(): string[] {
  const ordered = [MODEL_ID, ...FALLBACK_MODEL_IDS]
  return Array.from(new Set(ordered.filter(Boolean)))
}

function getErrorStatusCode(err: unknown): number | null {
  if (typeof err !== 'object' || err === null) return null
  const raw = (err as { statusCode?: unknown }).statusCode
  return typeof raw === 'number' ? raw : null
}

function getErrorMessage(err: unknown): string {
  if (err instanceof Error) return err.message
  return String(err)
}

export interface DialogueSegment {
  speaker: 'HOST' | 'COHOST'
  text: string
  index: number
}

export function parseDialogue(script: string): DialogueSegment[] {
  const lines = script
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)

  const segments: DialogueSegment[] = []
  let index = 0

  for (const line of lines) {
    if (line.startsWith('[HOST]')) {
      segments.push({
        speaker: 'HOST',
        text: line.replace('[HOST]', '').trim(),
        index: index++,
      })
      continue
    }

    if (line.startsWith('[COHOST]')) {
      segments.push({
        speaker: 'COHOST',
        text: line.replace('[COHOST]', '').trim(),
        index: index++,
      })
    }
  }

  if (segments.length === 0) {
    segments.push({
      speaker: 'HOST',
      text: script.trim(),
      index: 0,
    })
  }

  return segments
}

async function generateSegmentAudio(
  text: string,
  voiceId: string,
  ownerId: string,
  segIndex: number,
): Promise<{ buffer: Buffer; filePath: string }> {
  let audioStream: Awaited<ReturnType<typeof eleven.textToSpeech.convertAsStream>> | null = null
  let lastError: unknown = null

  for (const modelId of getModelChain()) {
    try {
      audioStream = await eleven.textToSpeech.convertAsStream(voiceId, {
        text,
        model_id: modelId,
        voice_settings: {
          stability: 0.5,
          similarity_boost: 0.75,
          style: 0.3,
          use_speaker_boost: true,
        },
        output_format: 'mp3_44100_128',
      })
      break
    } catch (err) {
      lastError = err
      const statusCode = getErrorStatusCode(err)
      const message = getErrorMessage(err)

      // 402/422/404 often mean model-plan mismatch or unavailable model; try next model.
      if (statusCode === 402 || statusCode === 422 || statusCode === 404) {
        console.warn(`[ElevenLabs] model=${modelId} unavailable for this account, trying fallback`) 
        continue
      }

      throw err
    }
  }

  if (!audioStream) {
    throw lastError ?? new Error('Failed to generate audio stream from ElevenLabs')
  }

  const chunks: Buffer[] = []
  for await (const chunk of audioStream) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk))
  }

  const buffer = Buffer.concat(chunks)
  const fileName = `${uuidv4()}-seg${segIndex}.mp3`
  const filePath = `${ownerId}/segments/${fileName}`

  const { error } = await supabase.storage
    .from(STORAGE_BUCKET)
    .upload(filePath, buffer, {
      contentType: 'audio/mpeg',
      cacheControl: '3600',
      upsert: false,
    })

  if (error) {
    throw new Error(`[ElevenLabs] Segment upload failed: ${error.message}`)
  }

  return { buffer, filePath }
}

export interface AnswerAudioResult {
  audioUrl: string
  filePath: string
  durationSecs: number
  charCount: number
}

export async function generateAnswerAudio(
  answerText: string,
  ownerId: string,
): Promise<AnswerAudioResult> {
  const { buffer, filePath } = await generateSegmentAudio(
    answerText,
    VOICE_IDS.ANSWER,
    ownerId,
    Date.now(),
  )

  const {
    data: { publicUrl },
  } = supabase.storage.from(STORAGE_BUCKET).getPublicUrl(filePath)

  return {
    audioUrl: publicUrl,
    filePath,
    durationSecs: Math.max(1, Math.ceil(buffer.length / 16000)),
    charCount: answerText.length,
  }
}

export interface PodcastSegmentResult {
  speaker: 'HOST' | 'COHOST'
  audioUrl: string
  filePath: string
  text: string
  index: number
}

export interface PodcastResult {
  segments: PodcastSegmentResult[]
  totalChars: number
  segmentCount: number
}

export async function generatePodcastSegments(
  script: string,
  ownerId: string,
): Promise<PodcastResult> {
  const dialogue = parseDialogue(script)
  const segments: PodcastSegmentResult[] = []
  let totalChars = 0

  console.log(`[ElevenLabs] Generating ${dialogue.length} segments for owner ${ownerId}`)

  for (const seg of dialogue) {
    const voiceId = seg.speaker === 'HOST' ? VOICE_IDS.HOST : VOICE_IDS.COHOST

    const { filePath } = await generateSegmentAudio(seg.text, voiceId, ownerId, seg.index)

    const {
      data: { publicUrl },
    } = supabase.storage.from(STORAGE_BUCKET).getPublicUrl(filePath)

    segments.push({
      speaker: seg.speaker,
      audioUrl: publicUrl,
      filePath,
      text: seg.text,
      index: seg.index,
    })

    totalChars += seg.text.length
  }

  console.log(`[ElevenLabs] Generated ${segments.length} segments, ${totalChars} total chars`)

  return {
    segments,
    totalChars,
    segmentCount: segments.length,
  }
}
